# Individual Feature Determination

## Preparation

### Import

In [1]:
import pandas as pd
import numpy as np
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Function Definition

### Calculate Group Features

In [2]:
def calc_group_features(indiv_features_file, file_out):

  df_indiv = pd.read_excel(indiv_features_file, index_col=0, usecols=["ID", "Group",  "TOTAL TEORÍA (6)", "TRABAJO FINAL (1)","TOTAL CURSO"])

  df_indiv['TOTAL CURSO'] = pd.to_numeric(df_indiv['TOTAL CURSO'], errors='coerce')
  filtered_df = df_indiv[df_indiv['TOTAL CURSO'].notnull()]

  df_indiv['TOTAL TEORÍA (6)'] = df_indiv['TOTAL TEORÍA (6)'] / 6
  df_indiv['TRABAJO FINAL (1)'] = df_indiv['TRABAJO FINAL (1)'] / 10
  df_indiv['TOTAL CURSO'] = df_indiv['TOTAL CURSO'] / 10

  df_group = df_indiv.groupby('Group').agg({'TOTAL TEORÍA (6)': [('mean_theory', 'mean'), ('max_theory', 'max'), ('min_theory', 'min')],'TRABAJO FINAL (1)': [('final_project', 'mean')]})
  column_names=df_group.columns.tolist()
  final_column_names = [col[1] for col in column_names]
  df_group.columns = final_column_names
  #df_group['final_project_minus_avg_theory'] = df_group['final_project'] - df_group['avg_theory']
  #df_group['final_project_minus_0.5_avg_theory'] = df_group['final_project'] - (df_group['avg_theory'] * 0.5)

  df_group.to_csv(file_out,encoding='utf-8-sig')

  return df_group

## Use of Function

In [3]:
indiv_features_file = r'/content/drive/MyDrive/Projects/tps/grades/data/1_participants_grades.xlsx'
file_out= r'/content/drive/MyDrive/Projects/tps/grades/data/2_group_grades.xlsx'

In [4]:
calc_group_features(indiv_features_file, file_out)

                   mean_theory  max_theory  min_theory  final_project
Group
GM BEAUVOIR           0.634000    0.703333    0.573333           0.80
GM CHOMSKY            0.701000    0.888333    0.513333           0.85
GM DESCARTES          0.793333    0.928333    0.636667           0.80
GM FOUCAULT           0.591667    0.648333    0.551667           0.70
GM KANT               0.599333    0.686667    0.500000           0.70
GM MINSKY             0.479000    0.708333    0.000000           0.87
GM PARMÉNIDES         0.798333    0.923333    0.720000           0.88
GM SÓCRATES           0.631111    0.806667    0.500000           0.80
GM WOLLSTONECRAFT     0.688333    0.751667    0.628333           0.68
GT HIPARQUIA          0.643611    0.820000    0.526667           0.60
GT SCHOPENHAUER       0.625000    0.873333    0.500000           0.90
GT ZAMBRANO           0.465556    0.708333    0.000000           0.70